remote_theme: ISSAE/architect

name: GlassFish

author: Saada Ibrahim

author_email: saada.ibrahim@isae.edu.lb

title: Le Serveur JavaEE Glassfish
google_analytics: UA-29708002-2

repository: ISSAE/Glassfish

plugins:
- jekyll-sitemap
